version: "3.1"
services:
    db:
        image: mysql:latest

        ports: 
            - "33306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbEmployee
            MYSQL_USER: rafa  #usuario santi
            MYSQL_PASSWORD: rafa #contraseña del usuario santi
            MYSQL_ROOT_PASSWORD: root #contraseña del root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin

        depends_on:
            - db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root #contraseña del root
volumes:
    persistent:

#docker-compose down -v  para que borre también los volúmenes en el caso de que quiera volver a lanzarlo.
#docker-compose up -d